apiVersion: v1
kind: Service
metadata:
  name: chat-frontend-client
spec:
  # type: LoadBalancer
  selector:
    app: chat-frontend-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
